- hosts: localhost
  gather_facts: no

  vars:
    freebox_url: http://mafreebox.freebox.fr

  tasks:
    
    - name: Get Freebox OS API version ('{{ freebox.url }}/api_version')
      uri:
        url: "{{ freebox_url }}/api_version"
        method: GET
      register: freebox_api

    - name: Set 'url_authorize' variable to '{{ freebox_url }}{{ freebox_api.json.api_base_url }}v{{ freebox_api.json.api_version.split('.')[0] }}/login/authorize'
      set_fact:
        url_authorize: "{{ freebox_url }}{{ freebox_api.json.api_base_url }}v4/login/authorize"

    - name: Get authorization for Freebox Ansible modules ('{{ url_authorize }}')
      uri:
        url: "{{ url_authorize }}"
        method: POST
        body_format: json
        body:
          app_id: com.ansible.modules.freebox
          app_name: Ansible modules for Freebox OS
          app_version: 4 
          #"{{ freebox_api.json.api_version.split('.')[0] }}"
          device_name: Ansible
      register: authorization
    
    - debug:
        msg: "{{ authorization }}"

    - debug:
        msg: |
          Freebox OS App Token: {{ authorization.json.result.app_token }}
          Track ID: {{ authorization.json.result.track_id }}